GET http://localhost:5000/authors

###
POST http://localhost:5000/authors
Content-Type: application/json

{
    "name": "Luca",
    "email": "sasf@adsad.it",
    "age": 53,
    "approved": true
}
###

DELETE http://localhost:5000/authors/66acf7150e43998c09109b1a

###

PUT http://localhost:5000/authors/66acf7150e43998c09109b1a
Content-Type: application/json

{
    "name" : "Giovanni"
}

###

GET http://localhost:5000/authors/?perPage=3

###

GET http://localhost:5000/authors/66acf7150e43998c09109b1a/blogPosts
