GET http://localhost:5000/authors/66d415a4177d1b6c086450e1

###
POST http://localhost:5000/authors
Content-Type: application/json

{
    "name": "Sempronio",
    "email": "sasf@asdfsadfsadfad.it",
    "age": 66,
    "approved": true,
    "avatar" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpH62QXSB-NmfDAiDi0aVt3QL-czqizleZAA&s"
}
###

DELETE http://localhost:5000/authors/66ad07bacd5d42bc148b217e

###

PUT http://localhost:5000/authors/66d415a4177d1b6c086450e1
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDQxNWE0MTc3ZDFiNmMwODY0NTBlMSIsImlhdCI6MTcyNTE4NzU3NSwiZXhwIjoxNzI1MTkxMTc1fQ.ipWMtpa-m5bk8HdWoOwlta2Ee375Z8xp_0gNwuHIvPU"

{
    "name" : "567"
}

###

GET http://localhost:5000/authors/?perPage=10

###

GET http://localhost:5000/authors/66d415a4177d1b6c086450e1/blogPosts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDQxNWE0MTc3ZDFiNmMwODY0NTBlMSIsImlhdCI6MTcyNTE4ODQwNCwiZXhwIjoxNzI1MTkyMDA0fQ.bwXASpu0uKtNqSdsRnMFdsxe8Yfle8BkxPrtzd8hxdE

###

// AUTHENTICATION
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Claudio",
    "password": "qwerty",
    "email": "claudio@gmail.it",
    "age": 66
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "claudio@gmail.it",
    "password": "qwerty"
}
