GET http://localhost:5000/authors/66d415a4177d1b6c086450e1

###
POST http://localhost:5000/authors
Content-Type: application/json

{
    "name": "ciao",
    "surname": "ciao2",
    "email": "ciao0000.it",
    "age": 66,
    "approved": true,
    "password": "123"
}
###

DELETE http://localhost:5000/authors/66ad07bacd5d42bc148b217e

###

PUT http://localhost:5000/authors/66d415a4177d1b6c086450e1
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDQxNWE0MTc3ZDFiNmMwODY0NTBlMSIsImlhdCI6MTcyNTE4NzU3NSwiZXhwIjoxNzI1MTkxMTc1fQ.ipWMtpa-m5bk8HdWoOwlta2Ee375Z8xp_0gNwuHIvPU"

{
    "name" : "567"
}

###

GET http://localhost:5000/authors/?perPage=10

###

GET http://localhost:5000/authors/66d415a4177d1b6c086450e1/blogPosts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDQxNWE0MTc3ZDFiNmMwODY0NTBlMSIsImlhdCI6MTcyNTE5OTQwMSwiZXhwIjoxNzI1MjAzMDAxfQ.Wg1Z04yjORS3sF44nWHDJ-giXE38zq-rJ-sa_P7MEW8

###

// AUTHENTICATION
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "ciao",
    "surname": "ciao",
    "password": "qwerty",
    "email": "ciaoooo@gmail.it",
    "age": 66
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "claudio@gmail.it",
    "password": "qwerty"
}

###

GET http://localhost:5000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDQxNWE0MTc3ZDFiNmMwODY0NTBlMSIsImlhdCI6MTcyNTIwMDY5MCwiZXhwIjoxNzI1MjA0MjkwfQ.XtpU3Kx5ftTLvi54t750H8DketmEcxhO6nfctsfh0gQ

