GET http://localhost:5000/blogPosts/?perPage=10

###

POST http://localhost:5000/blogPosts

Content-Type: application/json

{
    "title": "blu",
    "author" : "pincos@gmail.com",
}
###

DELETE http://localhost:5000/blogPosts/66ccb19aead46d287b0c2d23

###

PUT http://localhost:5000/blogPosts/66b12db996dc33e858d9d578

Content-Type: application/json

{
    "title" : "Kitchen"
}

###

GET http://localhost:5000/blogPosts?perPage=3&title=prato