GET http://localhost:5000/blogPosts/?perPage=10

###

GET http://localhost:5000/blogPosts/66d43c52c71222094950c7de
###

POST http://localhost:5000/blogPosts
Content-Type: application/json


{
    "category": "categoria 1",
    "title": "bo Post",
    "cover":"",
    "readTime":{
        "value" : 5,
        "unit" : "min"
    },
    "author": "66d415a4177d1b6c086450e1",
    "content": "ciaooo"

}
###
DELETE http://localhost:5000/blogPosts/66cde5510f768a29062566c3

###

PUT http://localhost:5000/blogPosts/66b12db996dc33e858d9d578
Content-Type: application/json

{
    "title" : "Kitchen"
}

###

GET http://localhost:5000/blogPosts?perPage=3&title=prato

###
POST http://localhost:5000/blogPosts/66bf939feeeb01604d9b1f1c/comments
Content-Type: application/json

{
    "content": "terzo commento"
}
###
GET http://localhost:5000/blogPosts/66bf939feeeb01604d9b1f1c/comments

###
GET http://localhost:5000/blogPosts/66bf939feeeb01604d9b1f1c/comments/66ce03533aaa74ed5f8d2464

###
PUT http://localhost:5000/blogPosts/66bf939feeeb01604d9b1f1c/comments/66ce03533aaa74ed5f8d2464
Content-Type: application/json

{
    "content": "commento modificato"
}
###
DELETE http://localhost:5000/blogPosts/66bf939feeeb01604d9b1f1c/comments/66ce03483aaa74ed5f8d2462