GET http://localhost:5000/blogPosts

###

POST http://localhost:5000/blogPosts

Content-Type: application/json

{
    "category": "Home",
    "title": "Kitchen",
    "cover": "https://www.riccicasa.it/wp-content/uploads/2021/07/cucina-bellary-frassino-biancospino.jpg",
    "readTime": {
        "value" : 8,
        "unit" : "min"
    },
    "author" : "66acf7150e43998c09109b1a",
    "content" : "Decorazione da cucina personalizzata di armadio integrale moderno tipo economico di armadio da cucina da appoggio in pietra di quarzo"
}
###

DELETE http://localhost:5000/blogPosts/66b2440d0c82c50b31222332

###

PUT http://localhost:5000/blogPosts/66b12db996dc33e858d9d578

Content-Type: application/json

{
    "title" : "Kitchen"
}

###

GET http://localhost:5000/blogPosts?perPage=3&title=prato